# This file was generated by GoReleaser. DO NOT EDIT.
cask "ndev" do
  version "0.1.3"

  on_macos do
    on_intel do
      url "https://github.com/noona-hq/ndev-releases/releases/download/v#{version}/ndev_#{version}_darwin_amd64.tar.gz"
      sha256 "01725480d4b2a42d05ccc9d766b1ef427f4008d1e02fe9c20678e42179533cce"
    end
    on_arm do
      url "https://github.com/noona-hq/ndev-releases/releases/download/v#{version}/ndev_#{version}_darwin_arm64.tar.gz"
      sha256 "be4c8e9bcb85812c4b24395dc5ea821c72b6f3b36c58a3dfe0067882e051823e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/noona-hq/ndev-releases/releases/download/v#{version}/ndev_#{version}_linux_amd64.tar.gz"
      sha256 "e8f69c7113e0fda246bdfa6f31d9e44af07a86d198c0b74c050d5ae24ac39514"
    end
    on_arm do
      url "https://github.com/noona-hq/ndev-releases/releases/download/v#{version}/ndev_#{version}_linux_arm64.tar.gz"
      sha256 "40d1312791d12f6e9756f24b35a1e4674e3062a20605b640b4f3aed39acc321d"
    end
  end

  name "ndev"
  desc "Noona Local Development CLI"
  homepage "https://github.com/noona-hq/ndev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ndev"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ndev"]
    end
  end

  # No zap stanza required

end
