# This file was generated by GoReleaser. DO NOT EDIT.
cask "ndev" do
  version "0.1.9"

  on_macos do
    on_intel do
      sha256 "8c640b1e8f7ede88382dd43f98ce3375e86953390026f44c081277523f6e5136"
      url "https://github.com/noona-hq/ndev-releases/releases/download/v#{version}/ndev_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e0f39863f952e3e4e3c7912bad616170e2d19b51f0fcc9664bbcdebcd834fbbb"
      url "https://github.com/noona-hq/ndev-releases/releases/download/v#{version}/ndev_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b58cfb916c87bc427ec82052feb15143f29745c664ec62f38b8f0af103c1e253"
      url "https://github.com/noona-hq/ndev-releases/releases/download/v#{version}/ndev_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "401d471b2f0ba5146d27499c20f438ab82f9f8a57fad7aaab37bd757c8f2469b"
      url "https://github.com/noona-hq/ndev-releases/releases/download/v#{version}/ndev_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ndev"
  desc "Noona Local Development CLI"
  homepage "https://github.com/noona-hq/ndev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ndev"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ndev"]
    end
  end

  # No zap stanza required

end
