# This file was generated by GoReleaser. DO NOT EDIT.
cask "ndev" do
  version "0.2.1"

  on_macos do
    on_arm do
      sha256 "0454c42e9c4eeabdc3a4bc8a896789ad435bac7525e8328e89585ffaae514b2a"
      url "https://github.com/noona-hq/ndev-releases/releases/download/v#{version}/ndev_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "77b059b7f94ce529a48acbcb9ad9482ce8c497512687ef1f750eaaa8bba0557f"
      url "https://github.com/noona-hq/ndev-releases/releases/download/v#{version}/ndev_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ffeb37b70220fc48f0d6c359185a9ce81df2f780fabec29d4f0233ed7c13c641"
      url "https://github.com/noona-hq/ndev-releases/releases/download/v#{version}/ndev_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f793fb158bb7bf9b4c4f22d9e8880285b92752e871b6b4213e1b48f09bc06bf5"
      url "https://github.com/noona-hq/ndev-releases/releases/download/v#{version}/ndev_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ndev"
  desc "Noona Local Development CLI"
  homepage "https://github.com/noona-hq/ndev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ndev"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ndev"]
    end
  end

  # No zap stanza required
end
